GymApp/Controllers/BodyPartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GymApp.Data;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace GymApp.Controllers
{
    public class BodyPartController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BodyPartController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var bodyParts = _context.BodyParts.ToList();
            return View(bodyParts);
        }
    }
}

GymApp/Controllers/ExerciseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GymApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace GymApp.Controllers
{
    public class ExerciseController : Controller
    {
        private readonly ApplicationDbContext _context;
        // GET: /<controller>/

        public ExerciseController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(int? bodyPartId)
        {

            var exercises = await _context.Exercises
                .Include(e => e.BodyPart)
                .Include(e => e.RecordHolder)
                .ToListAsync();

            if (bodyPartId.HasValue)
            {
                exercises = exercises.Where(e => e.BodyPartId == bodyPartId).ToList();
            }

            return View(exercises);
        }
    }
}

GymApp/Controllers/TrainingController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using GymApp.Data;
using GymApp.Models;

namespace GymApp.Controllers
{
    public class TrainingController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<User> _userManager;

        public TrainingController(ApplicationDbContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var trainings = await _context.Trainings
                .Where(t => t.UserId == userId)
                .ToListAsync();

            return View(trainings);
        }
        
        public IActionResult Create()
        { 
            var viewModel = new Training();
            viewModel.TrainingExercises = new List<TrainingExercises>(); // Inicjalizacja listy

            return View(viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name")] Training training)
        {

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            training.UserId = userId;
            training.CreateDate = DateTime.Now;

            _context.Add(training);
            await _context.SaveChangesAsync();

  
            return RedirectToAction(nameof(Index));

              
        }


         public IActionResult Details(int id)
         {
            var trainingExercises = _context.TrainingExercises
                .Include(te => te.Exercise)
                .Where(te => te.TrainingId == id)
                .ToList();

                 ViewBag.TrainingId = id; // Przekazujemy id treningu do widoku, aby można było dodać nowe ćwiczenia

                 return View(trainingExercises);
         }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var training = await _context.Trainings
                        .Include(t => t.TrainingExercises)
                        .FirstOrDefaultAsync(t => t.Id == id);

            if (training == null)
            {
                return NotFound();
            }

            // Usuwanie powiązanych TrainingExercises
            _context.TrainingExercises.RemoveRange(training.TrainingExercises);

            _context.Trainings.Remove(training);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

            [HttpPost]
            [ValidateAntiForgeryToken]
            public IActionResult DeleteExercise(int trainingId, int exerciseId)
            {
                var trainingExercise = _context.TrainingExercises
                    .FirstOrDefault(te => te.TrainingId == trainingId && te.ExerciseId == exerciseId);

                if (trainingExercise == null)
                {
                    return NotFound();
                }

                _context.TrainingExercises.Remove(trainingExercise);
                _context.SaveChanges();

                return RedirectToAction("Details", new { id = trainingId });
            }
        

       












    }
}

GymApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GymApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GymApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GymApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="BodyPart" asp-action="Index">Partie Ciała</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Exercise" asp-action="Index">Ćwiczenia</a>
                        </li>
                        <li class="nav-item">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <a class="nav-link text-light" asp-area="" asp-controller="Training" asp-action="Index">Moje treningi</a>
                            }
                        </li>
                        <li class="nav-item">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <a class="nav-link text-light" asp-area="" asp-controller="TrainingSession" asp-action="Index">Pokaż moje sesje</a>
                            }
                        </li>
                        <li class="nav-item">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <a class="nav-link text-light" asp-area="" asp-controller="TrainingSession" asp-action="Create">Dodaj sesję</a>
                            }
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - GymApp - Mateusz Nowak & Zbigniew Skrzypczak
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>